# Generated by Django 2.0.5 on 2018-05-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pergunta_1', models.CharField(choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, verbose_name='Texto da pergunta 1')),
                ('pergunta_2', models.CharField(choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, verbose_name='Texto da pergunta 1')),
                ('pergunta_3', models.CharField(choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, verbose_name='Texto da pergunta 1')),
                ('pergunta_4', models.CharField(choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, verbose_name='Texto da pergunta 1')),
                ('pontuacao', models.IntegerField()),
            ],
        ),
    ]
