# Generated by Django 2.0.5 on 2018-05-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_1',
            field=models.CharField(blank=True, choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_2',
            field=models.CharField(blank=True, choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_3',
            field=models.CharField(blank=True, choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_4',
            field=models.CharField(blank=True, choices=[('1', 'Resposta 1'), ('2', 'Resposta 2'), ('3', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pontuacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
