# Generated by Django 2.0.5 on 2018-05-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180506_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_1',
            field=models.CharField(blank=True, choices=[('0', 'Resposta 1'), ('10', 'Resposta 2'), ('0', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_2',
            field=models.CharField(blank=True, choices=[('0', 'Resposta 1'), ('10', 'Resposta 2'), ('0', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_3',
            field=models.CharField(blank=True, choices=[('0', 'Resposta 1'), ('10', 'Resposta 2'), ('0', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_4',
            field=models.CharField(blank=True, choices=[('0', 'Resposta 1'), ('10', 'Resposta 2'), ('0', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pontuacao',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
