# Generated by Django 2.0.5 on 2018-05-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionario_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='id',
        ),
        migrations.AlterField(
            model_name='questionario',
            name='numero',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Número de matrícula'),
        ),
    ]
