# Generated by Django 2.0.5 on 2018-05-16 01:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20180515_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 1'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_10',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 10'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 2'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 3'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 4'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 5'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_6',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 6'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_7',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 7'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_8',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 8'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_9',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Resposta 1'), ('10', 'Resposta 2'), ('2', 'Resposta 3')], max_length=200, null=True, verbose_name='Texto da pergunta 9'),
        ),
    ]
